config/routes.rb
SampleApp::Application.routes.draw do

  root :to => 'home#index'
  
  match '/art', :to => 'art#index'
  
  resources :posts

  resources :users
    
  match '/signup', :to => 'users#new' 
  get "random/index"
  get "random/show"
  
  match '/sandbox', :to => 'pages#sandbox'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/thoughts',    :to => 'pages#thoughts'
  match '/photos', :to => 'pages#photos'
  match '/benny', :to => 'pages#benny'
  match '/goals', :to => 'pages#goals'
  
  match '/photos/cascade-falls', :to => 'pages#cascade'

  match '/thoughts/roll-your-own-kinda', :to => 'pages#thoughts_roll_your_own'
  
end

app/views/pages/about.html.erb
<div class="container">
<h2 class="happy">Hi, I'm Cam!</h2>
<%= render 'layouts/aboutme' %>

<hr>

<div class="row">
<div class="span5 well">
<h2 class="happy">To do list</h2>
<hr>
<h3>Adventures</h3>
 
<ul>
  <li>Save enough money to take my wonderful wife Cary on a honeymoon</li>
  <li>Go fly fishing for trout down near the secret spot in santa cruz chuck told me about</li>
	<li>Find and name a mushroom new to science</li>
</ul>

<hr>
<h3>Physical</h3>
 
<ul>
  <li>Play squash again (why can't I play? I tore a tendon in my elbow while chopping down a tree to prove to my wife's father I was manly enough to deserve her hand in marriage)</li>
  <li>Hike and take photos at least once a week</li>
</ul>

<hr>

<h3>Work Now</h3>
 
<ul>
  <li>Cost effective customer acquisition and retention</li>
  <li>Create beautiful, groundbreaking and functional products</li>
	<li>Use data and connections to personalize </li>
  <li>Create the best online wine community</li>
</ul>

<hr>

<h3>Work Later</h3>
 
<ul>
  <li>Start or be a part of something from the beginning that matters. I want to die knowing I decreased entropy in my tiny part of the universe.</li>
</ul>

</div>
<div class="span5 well">
<h2 class="happy">About this site <small>hand crafted by cam</small></h2>
<hr>
<ul>
<li>web framework: <a href="http://rubyonrails.org/">ruby on rails</a></li>
<li>front end framework: <a href="http://twitter.github.com/bootstrap/">twitter bootstrap</a></li>
<li>versioning and repository: <a href="http://www.github.com/camfortin">github</a></li>
<li>hosting: <a href="http://heroku.com">heroku</a></li>
</ul>
</div>
</div>

</div>
</div>

app/views/pages/benny.html.erb
<div class="container">

<h3 style="color:gray">The Benny Love Generator</h3>

<hr>
<div class="row" >
	
	 <div class="span6 alert alert-info happy">
			<h2><%= random %></h2>
		<br />
		<%= link_to "Do it again!", benny_path, :class => "btn btn-large btn-primary"%>
	</div>
	
	<div class="span4 well">
    <h3 style="color:gray">"love is all you need"</h3>
		<br />
		<p style="color:gray">Welcome to the family <a href="http://www.theedmondsfamily.com/">benny</a>! If you ever need some love just visit this page and hit the "do it again" button for as long as you want!</p>
		<p style="color:gray" class="pull-right">Built with love by your uncle <a href="http://www.steepravine.com">Cam</a></p>
	</div>
	
</div>


</div>

app/views/pages/cascade.html.erb
<h1>Cascade Falls Mushroom Hunt</h1>

<p>I went on a fantastic loop from cascade falls to the fire station on pantoll and back down on another small trail. perfection with mushrooms and waterfalls everywhere.</p>

<p>I ended up finding more mushrooms than anticipated, and I wish I had brought some home with me as soon as I got home and realized a few were choice edibles (candy caps and hedgehog mushrooms). I also found a few tiny "earpick" mushrooms growing out of a douglas fir cone, they are the solitary species of their genus and have incredible looking spore spikes hanging down from their kidney shaped caps.</p>

<h3>Slideshow</h3>

<object width="800" height="600"> <param name="flashvars" value="offsite=true&lang=en-us&page_show_url=%2Fphotos%2Ffriendshipgoodtimes%2Fsets%2F72157629244046090%2Fshow%2F&page_show_back_url=%2Fphotos%2Ffriendshipgoodtimes%2Fsets%2F72157629244046090%2F&set_id=72157629244046090&jump_to="></param> <param name="movie" value="http://www.flickr.com/apps/slideshow/show.swf?v=109615"></param> <param name="allowFullScreen" value="true"></param><embed type="application/x-shockwave-flash" src="http://www.flickr.com/apps/slideshow/show.swf?v=109615" allowFullScreen="true" flashvars="offsite=true&lang=en-us&page_show_url=%2Fphotos%2Ffriendshipgoodtimes%2Fsets%2F72157629244046090%2Fshow%2F&page_show_back_url=%2Fphotos%2Ffriendshipgoodtimes%2Fsets%2F72157629244046090%2F&set_id=72157629244046090&jump_to=" width="800" height="600"></embed></object>
<p class = "soft"><a href="http://www.flickr.com/photos/friendshipgoodtimes/sets/72157629244046090/with/6992018135/">No slideshow? View it on flickr: cascade falls mushroom hunt</a></p>

<h3>Natural Bridge</h3>
<a href="http://www.flickr.com/photos/friendshipgoodtimes/6992018135/" title="Natual Bridge by camfortin, on Flickr"><img src="http://farm8.staticflickr.com/7176/6992018135_0c448487a7_b.jpg" width="100%" alt="Natual Bridge"></a>
<p></p>
<h3>Earpick Fungus growing out of Douglas Fir Cone</h3>
<a href="http://www.flickr.com/photos/friendshipgoodtimes/6845902546/" title="Earpick Fungus Growing out of Douglas Fir Cones by camfortin, on Flickr"><img src="http://farm8.staticflickr.com/7059/6845902546_ec16c0d695_b.jpg" width="100%" alt="Earpick Fungus Growing out of Douglas Fir Cones"></a>
<p></p>
<h3>Hedgehog Mushrooms</h3>
<a href="http://www.flickr.com/photos/friendshipgoodtimes/6845908190/" title="Hedgehog Mushrooms by camfortin, on Flickr"><img src="http://farm8.staticflickr.com/7054/6845908190_90eae6f01a_b.jpg" width="100%" alt="Hedgehog Mushrooms"></a>
<p></p>
<h3>Candy Caps</h3>
<a href="http://www.flickr.com/photos/friendshipgoodtimes/6845910114/" title="Candy Cap Family by camfortin, on Flickr"><img src="http://farm8.staticflickr.com/7177/6845910114_ef88b6145d_b.jpg" width="100%" alt="Candy Cap Family"></a>
<p></p>
<h3>Red Mushroom Side</h3>
<a href="http://www.flickr.com/photos/friendshipgoodtimes/6845912420/" title="Red Mushroom Side by camfortin, on Flickr"><img src="http://farm8.staticflickr.com/7036/6845912420_f73c3d4c8e_b.jpg" width="100%" alt="Red Mushroom Side"></a>
<p></p>
<h3>Coral Fungus</h3>
<a href="http://www.flickr.com/photos/friendshipgoodtimes/6992046473/" title="Coral Mushroom by camfortin, on Flickr"><img src="http://farm8.staticflickr.com/7059/6992046473_0dfaa9b626_b.jpg" width="100%" alt="Coral Mushroom"></a>
<p></p>
<h3>Log Jam!</h3>
<a href="http://www.flickr.com/photos/friendshipgoodtimes/6845916078/" title="Log Pile by camfortin, on Flickr"><img src="http://farm8.staticflickr.com/7190/6845916078_03a25f323e_b.jpg" width="100%" alt="Log Pile"></a>

app/views/pages/cheats.html.erb
<div class="container">
<h2 class="happy">Cam's Cheats</h2>
</div>

<hr>

<div class="row">
<div class="span2">
<h3 class ="happy">GitHub</h3>
</div>
<div class="span10">
<div class="well">
<ul>
<li>git push heroku git@github.com:camfortin/sample_app.git</li>
<li>one of these days I should switch the reference...</li>
</ul>

<hr>
<h2 class="happy">Upgrades to this site</h2>

<hr>

<h3>blog</h3>
<ul>
	<li>use stringex to make friendly blog urls</li>
	<li>finish layouts</li>
	<li>add authentication (devise) so I can add posts from anywhere</li>
	<li>add <a href="http://fancybox.net/">fancybox</a> to display image galleries</li>
</ul>

<hr>

<h3>projects</h3>
<ul>
	<li>wireframe a "projects" page and build it with jquery carousels etc</li>
	<li>figure out how to use <a href="http://www.1stwebdesigner.com/css/top-jquery-chart-libraries-interactive-charts/"</a>jquery charts</li>
	<li>use <a href="https://github.com/JoelBesada/scrollpath">scroll path</a> in a cool project</li>
</ul>

<hr>


</div>
</div>

</div>

app/views/pages/contact.html.erb
<h1>Virtually Me!</h1>
<p><a href="mailto:cam.fortin@gmail.com">email me</a><p>
<p><a href="http://www.twitter.com/#!/camfortin">@camfortin</a> | <a href="http://www.funjai.com">my tumblr</a> (mostly photos of the bay area)<p>

app/views/pages/fluid.html.erb
<div class="row-fluid">
  <div class="span3">
    <div class="well sidebar-nav">
      <ul class="nav nav-list">
        <li class="nav-header">Sidebar</li>
        <li class="active"><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li class="nav-header">Sidebar</li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li class="nav-header">Sidebar</li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
      </ul>
    </div><!--/.well -->
  </div><!--/span-->
  <div class="span9">
    <div class="hero-unit">
      <h1>Hello, world!</h1>
      <p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
      <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>
    </div>
    <div class="row-fluid">
      <div class="span4">
        <h2>Heading</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn" href="#">View details &raquo;</a></p>
      </div><!--/span-->
      <div class="span4">
        <h2>Heading</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn" href="#">View details &raquo;</a></p>
      </div><!--/span-->
      <div class="span4">
        <h2>Heading</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn" href="#">View details &raquo;</a></p>
      </div><!--/span-->
    </div><!--/row-->
    <div class="row-fluid">
      <div class="span4">
        <h2>Heading</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn" href="#">View details &raquo;</a></p>
      </div><!--/span-->
      <div class="span4">
        <h2>Heading</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn" href="#">View details &raquo;</a></p>
      </div><!--/span-->
      <div class="span4">
        <h2>Heading</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn" href="#">View details &raquo;</a></p>
      </div><!--/span-->
    </div><!--/row-->
  </div><!--/span-->
</div><!--/row-->

<hr>

<footer>
  <p>&copy; Company 2012</p>
</footer>

app/views/pages/goals.html.erb
<div class="container">
<h2 class="happy">Hi, I'm Cam!</h2>
<%= render 'layouts/aboutme' %>

<hr>

<div class="row">
<div class="span5 well">
<h2 class="happy">To do list</h2>
<hr>
<h3>Adventures</h3>
 
<ul>
  <li>Save enough money to take my wonderful wife Cary on a honeymoon</li>
  <li>Go fly fishing for trout down near the secret spot in santa cruz chuck told me about</li>
	<li>Find and name a mushroom new to science</li>
</ul>

<hr>
<h3>Physical</h3>
 
<ul>
  <li>Play squash again (why can't I play? I tore a tendon in my elbow while chopping down a tree to prove to my wife's father I was manly enough to deserve her hand in marriage)</li>
  <li>Hike and take photos at least once a week</li>
</ul>

<hr>

<h3>Work Now</h3>
 
<ul>
  <li>Cost effective customer acquisition and retention</li>
  <li>Create beautiful, groundbreaking and functional products</li>
	<li>Use data and connections to personalize </li>
  <li>Create the best online wine community</li>
</ul>

<hr>

<h3>Work Later</h3>
 
<ul>
  <li>Start or be a part of something from the beginning that matters. I want to die knowing I decreased entropy in my tiny part of the universe.</li>
</ul>

</div>
<div class="span5 well">
<h2 class="happy">About this site <small>hand crafted by cam</small></h2>
<hr>
<ul>
<li>web framework: <a href="http://rubyonrails.org/">ruby on rails</a></li>
<li>front end framework: <a href="http://twitter.github.com/bootstrap/">twitter bootstrap</a></li>
<li>versioning and repository: <a href="http://www.github.com/camfortin">github</a></li>
<li>hosting: <a href="http://heroku.com">heroku</a></li>
</ul>
</div>
</div>

</div>
</div>

app/views/pages/home.html.erb
<div class="container">
<h2 class="happy">welcome to camfortin.com</h2>
<%= render 'layouts/aboutme' %>
</div>
<hr>

<div class="container">
<div class="row">
	<div class="span12">
<a href="http://www.flickr.com/photos/friendshipgoodtimes/6288709507/" title="Bridge and Lights in the Headlands by camfortin, on Flickr"><img src="http://farm7.staticflickr.com/6095/6288709507_749f5e0486_b.jpg" width="100%" alt="Bridge and Lights in the Headlands"></a>
</div>
</div>
<br />
<hr>
<div class="container">
<div class="row">
	<div class="span8 offset2">
		<h4 class="happy" style="padding-bottom:10px">Salmon Fishing out of Half Moon Bay</h4>
		<a href="http://www.flickr.com/photos/friendshipgoodtimes/7186204838/" title="Half Moon Bay Salmon by camfortin, on Flickr"><img src="http://farm6.staticflickr.com/5453/7186204838_ced3579892_c.jpg" width="100%" alt="Half Moon Bay Salmon"></a>
		</div>
		</div>
		<hr>
	<div class="row">
	<div class="span8 offset2">
	<h4 class="happy" style="padding-bottom:10px">Tiny Sailboat and Big Foggy Bridge</h4>
	<a href="http://www.flickr.com/photos/friendshipgoodtimes/6842899172/" title="Foggy Golden Gate BW by camfortin, on Flickr"><img src="http://farm8.staticflickr.com/7048/6842899172_bdc934723f_c.jpg" width="100%" alt="Foggy Golden Gate BW"></a>
	</div>
</div>
<hr>
	<div class="row">
	<div class="span8 offset2">
	<h4 class="happy" style="padding-bottom:10px">Lupine Showing Off</h4>
<a href="http://www.flickr.com/photos/friendshipgoodtimes/7171361000/" title="Golden Gate Bridge and Purple Lupine by camfortin, on Flickr"><img src="http://farm6.staticflickr.com/5444/7171361000_691b4d5357_c.jpg" width="100%" alt="Golden Gate Bridge and Purple Lupine"></a>
  </div>
	</div>
</div>
<hr>
</div>

app/views/pages/photos.html.erb
<div class="container">
<h2 class="happy">"I'd Rather be Taking Photos"</h2>
<p>heaven is wandering around California with my camera</p>

<div class="row">
	
	<div class="span3">
		<h2><a href="http://www.flickr.com/photos/friendshipgoodtimes/sets/72157628412810149/">greatest hits</a></h2>
		<p>A flickr set of some of my favorite shots from all over the bay area.</p>
	</div>
	
	<div class="span3">
		<h2><a href="http://www.steepravine.com">steep ravine</a></h2>
		<p>My frequently updated tumblr of bay area photos. Mostly mushrooms, landscapes, night scenes and nature.</p>
	</div>
	
	<div class="span3">
		<h2><a href="http://humblephoto.com/">humble photo</a></h2>
		<p>My not-so-frequently updated 500px portfolio</p>
	</div>
	
	<div class="span3">
	<p class="alert alert-info">If you are interested in buying or using any of my photos please <a href="mailto:cam.fortin@gmail.com" class="happy">get in touch</a>, nothing makes me happier than sharing my work.</p>
	</div>
	
</div>
<a href="http://www.flickr.com/photos/friendshipgoodtimes/6509444937/" title="Angel Island to San Francisco: Bridge to Bridge by camfortin, on Flickr"><img src="http://farm8.staticflickr.com/7005/6509444937_343386a1d3_b.jpg" width="100%" alt="Angel Island to San Francisco: Bridge to Bridge"></a><p class="happy">taken from angel island on my 28th birthday</p>
<hr>
</div>
<div class="row">
	<div class="span6">
	  <h2 class="happy">Featured Slideshow</h2>
		<p>Mushrooms, my favorite subject</p>
	  <div id="myCarousel" class="carousel slide">
	    <div class="carousel-inner">
	      <div class="item active">
	        <img src="http://farm7.staticflickr.com/6097/6402904553_9fbf762c0f_z.jpg" alt="">
	      </div>
	      <div class="item">
	        <img src="http://farm9.staticflickr.com/8009/7641816610_d39385d57a_z.jpg" alt="">
	      </div>
	      <div class="item">
	        <img src="http://farm9.staticflickr.com/8145/7641718094_c0b3034bca_z.jpg" alt="">
	      </div>
	      <div class="item">
	        <img src="http://farm9.staticflickr.com/8422/7641830970_ce46f1c370_z.jpg">
	      </div>
	      <div class="item">
	        <img src="http://farm8.staticflickr.com/7124/7641820754_c3741ffe0e_z.jpg">
	      </div>
	      <div class="item">
	        <img src="http://farm8.staticflickr.com/7277/7641761698_75aa58b06f_z.jpg">
	      </div>

	    </div>
	    <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
	    <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
	</div>
	</div>
<div class="span6">
<h2 class="happy">Recent Favorite</h2>
<p>Saturated Golden Gate</p>
<a href="http://www.flickr.com/photos/friendshipgoodtimes/6828083023/" title="Saturated Golden Gate by camfortin, on Flickr"><img src="http://farm8.staticflickr.com/7156/6828083023_b661f81bae_z.jpg" width="100%" alt="Saturated Golden Gate"></a>
</div>


</div>

app/views/pages/thoughts.html.erb
<div class="container">
	<h1 class="happy">Thoughts & Ramblings</h1>
</div>
<hr>

<div class="row">
	<div class="span6">
		<div class="well">
		<h2>Recent Thoughts</h2>
		<p><a href="/thoughts/roll-your-own-kinda">"Roll Your Own Kinda"<a></p>
		</div>
	</div>
	<div class="span6">
	<div class="alert alert-info">
	<button class="close" data-dismiss="alert">×</button>
	<p>I'm still working on this section, but feel free to look around. I read non-fiction every night and do analysis all day. One of these days I'd like to apply my analytical abilities to the scientific and natural phenomenon that captivate me. The results will live here.</p>
	</div>
	</div>
</div>
<%= render 'layouts/aboutme' %>

app/views/pages/thoughts_roll_your_own.html.erb
<div class="container">
<h1 class="happy">Roll Your Own Kinda</h1>
<p>go build something. but don't re-invent the wheel.</p>
</div>
<hr>
<div class="container">
<p>If you get everything you ask for you will never learn a thing. If you build everything from scratch you will never build something very helpful. While that may seem like a paradox I don't think it really is.</p>
</div>