config/routes.rb
SampleApp::Application.routes.draw do

  root :to => 'home#index'
  
  match '/art', :to => 'art#index'
  
  resources :posts

  resources :users
    
  match '/signup', :to => 'users#new' 
  get "random/index"
  get "random/show"
  
  match '/sandbox', :to => 'pages#sandbox'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/thoughts',    :to => 'pages#thoughts'
  match '/photos', :to => 'pages#photos'
  match '/benny', :to => 'pages#benny'
  match '/goals', :to => 'pages#goals'
  
  match '/photos/cascade-falls', :to => 'pages#cascade'

  match '/thoughts/roll-your-own-kinda', :to => 'pages#thoughts_roll_your_own'
  
end

app/models/post.rb
class Post < ActiveRecord::Base
    
  attr_accessible :content, :title, :category, :tag_list
  acts_as_taggable
  acts_as_url :title
  def to_param
    url # or whatever you set :url_attribute to
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   http_basic_authenticate_with :name => "cam", :password => "password", :except => [:index, :show]
   #http_basic_authenticate_with :name => NAME, :password => "password", :except => [:index, :show]
  
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find_by_url(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find_by_url(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find_by_url(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find_by_url(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<h2>Add a new post</h2>
<hr>

<div class="well">
<%= form_for @post, :html => { :class => 'form-horizontal' } do |f| %>
 
<div class="field">
  <%= f.label :title %>
  <%= f.text_field :title, placeholder: "post title..." %></div>
<br />

<div class="field">
  <%= f.label :category %>
  <%= f.text_field :category, placeholder: "categories..." %></div>
<br />

<div class="field">
  <%= f.label :tag_list %>
  <%= f.text_field :tag_list, placeholder: "tags..." %></div>
<br />

<div class="field">
<%= f.label :content %>
  <%= f.text_area :content, placeholder: "post contnet...", class: "span4", :rows => 4 %>
</div>
<br />

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                posts_path, :class => 'btn' %>
  </div>
<% end %>
</div>

app/views/posts/edit.html.erb
<%- model_class = @post.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<%- model_class = Post.new.class -%>
<div class="container">
<h1 class="happy">Cam's Thoughts</h1>
<hr>
<div class="row span10 offset1 well">
	
    <% @posts.each do |post| %>
      <p><h2><%= link_to post.title, post_path(post) %></h2> (<%= link_to "edit", edit_post_path(post) %>)</p>
			<hr>
    <% end %>
</div>


<%= link_to t('.new', :default => t("helpers.links.new")),
            new_post_path,
            :class => 'btn btn-primary' %>
</div>

app/views/posts/new.html.erb
<%- model_class = @post.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<%- model_class = @post.class -%>

<div class="container">
<h2 class="happy"><%= @post.title %></h2>
<p><%= @post.tag_list.sample %></p>
<hr>
<div class="row">
<div class="span10 offset1">
<div class="well">
<%= raw @post.content %>
</div>
</div>
</div>

<hr>

<div class="container">
<p><a href="mailto:cam.fortin@gmail.com">email me</a> | <a href="http://www.twitter.com/#!/camfortin">@camfortin</a> | <a href="http://www.steepravine.com">my tumblr</a> | <%= link_to "personal goals", goals_path %></p>
</div>

<hr>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              posts_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_post_path(@post), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              post_path(@post),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>
</div>