config/routes.rb
SampleApp::Application.routes.draw do

  root :to => 'home#index'
  
  match '/art', :to => 'art#index'
  
  resources :posts

  resources :users
    
  match '/signup', :to => 'users#new' 
  get "random/index"
  get "random/show"
  
  match '/sandbox', :to => 'pages#sandbox'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/thoughts',    :to => 'pages#thoughts'
  match '/photos', :to => 'pages#photos'
  match '/benny', :to => 'pages#benny'
  match '/goals', :to => 'pages#goals'
  
  match '/photos/cascade-falls', :to => 'pages#cascade'

  match '/thoughts/roll-your-own-kinda', :to => 'pages#thoughts_roll_your_own'
  
end

app/views/layouts/_aboutme.html.erb
<p><a href="/photos">bay area photographer</a> | <a href="http://www.linkedin.com/in/camfortin">senior director of product development</a> at <a href="http://www.wine.com/v6/Screw-Cap-Wines/wine/list.aspx?N=7155+44&s=friends_cam&cid=friends_cam">wine.com</a> | <a href="http://www.steepravine.com">avid science and nature enthusiast</a> | <a href="/about"> aspiring hacker</a></p>

app/views/layouts/_footer.html.erb
<div class="container"><hr>
<footer>
				<a href="https://twitter.com/CamFortin" class="twitter-follow-button" data-show-count="false">@CamFortin</a> <p><%= Twitter.user_timeline("camfortin").first.text %></p>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
</footer>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/">cam fortin</a>
      <div class="nav-collapse">
        <ul class="nav">
	        <li><%= link_to "photos", photos_path %></li>
	        <li><%= link_to "about", about_path %></li>
	        <li><a href="https://twitter.com/CamFortin">@camfortin</a></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title><%= @title %></title>
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
	<%= render 'layouts/header' %>
	<div class="container">
	<%= yield %>
	</div>
	 <%= debug(params) if Rails.env.development? %>
  </body>
</html>